### ISSUE TITLE
Cornerstone in the MAC system environment, multiple image rendering problem

### ISSUE THREAD

**Issue by gjun-neusoft** [chafey/cornerstone#94] opened 2017-02-27 16:18 UTC
MAC system Safari browser, how long picture display, image loading sequence problems.
For example: at the same time load two pictures A and picture B, showing that the two picture B. Did not show picture A.
This problem exists only in the safari browser, in the Chrome browser normal display.
This problem will be more obvious in cornerstoneTools operation.

**Comment by jpambrun** [comment] 2017-02-27 16:23
@swederik Maybe related to the RequestAnimationFrame implementation? Unfortunately I cannot test in this environment.

**Comment by jpambrun** [comment] 2017-02-27 16:56
We were not able to reproduce, can you provide more information? Perhaps a minimal code example.

Thanks.

**Comment by swederik** [comment] 2017-04-06 07:32
I have managed to reproduce this, and indeed it is pretty bad. You need to show two images with the same dimensions and rendering path (i.e. both grayscale). One of them will suddenly jump back to displaying the contents of the other viewport.

It's fixed by https://github.com/chafey/cornerstone/pull/77 I believe.

**Comment by gjun-neusoft** [comment] 2017-04-06 07:46
The problem has been solved.
Thanks



g.jun@neusoft.com
 
From: Erik Ziegler
Date: 2017-04-06 15:32
To: chafey/cornerstone
CC: test; Author
Subject: Re: [chafey/cornerstone] Cornerstone in the MAC system environment, multiple image rendering problem (#94)
I have managed to reproduce this, and indeed it is pretty bad. You need to show two images with the same dimensions and rendering path (i.e. both grayscale). One of them will suddenly jump back to displaying the contents of the other viewport.
It's fixed by #77 I believe.
—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub, or mute the thread.
--> --> 
--> 


---------------------------------------------------------------------------------------------------
Confidentiality Notice: The information contained in this e-mail and any accompanying attachment(s)
is intended only for the use of the intended recipient and may be confidential and/or privileged of
Neusoft Corporation, its subsidiaries and/or its affiliates. If any reader of this communication is
not the intended recipient, unauthorized use, forwarding, printing,  storing, disclosure or copying
is strictly prohibited, and may be unlawful.If you have received this communication in error,please
immediately notify the sender by return e-mail, and delete the original message and all copies from
your system. Thank you.
---------------------------------------------------------------------------------------------------

**Comment by swederik** [comment] 2017-04-06 07:47
What do you mean? How?

**Comment by swederik** [comment] 2017-04-06 07:53
This is now fixed in the latest master by this commit: https://github.com/chafey/cornerstone/commit/5846cf0a5b6663c1bf0c9a7e145127b4abddd7fe

**Closed by swederik** 2017-04-06 07:53 UTC
Labels: bug

**Comment by gjun-neusoft** [comment] 2017-04-06 08:04
I have found a solution on GitHub, not in time to close bug, I am sorry



g.jun@neusoft.com
 
From: Erik Ziegler
Date: 2017-04-06 15:53
To: chafey/cornerstone
CC: test; Author
Subject: Re: [chafey/cornerstone] Cornerstone in the MAC system environment, multiple image rendering problem (#94)
Closed #94.
—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub, or mute the thread.
--> --> 
--> 


---------------------------------------------------------------------------------------------------
Confidentiality Notice: The information contained in this e-mail and any accompanying attachment(s)
is intended only for the use of the intended recipient and may be confidential and/or privileged of
Neusoft Corporation, its subsidiaries and/or its affiliates. If any reader of this communication is
not the intended recipient, unauthorized use, forwarding, printing,  storing, disclosure or copying
is strictly prohibited, and may be unlawful.If you have received this communication in error,please
immediately notify the sender by return e-mail, and delete the original message and all copies from
your system. Thank you.
---------------------------------------------------------------------------------------------------
