### ISSUE TITLE
Monochrome2 Dicom Images

### ISSUE THREAD

**Issue by MAhmedSaeed** [chafey/cornerstone#40] opened 2016-02-16 09:56 UTC
Monochrome2 Dicom Images don't displayed correcttly

**Comment by swederik** [comment] 2016-02-16 10:31
Hi Ahmed,

Does your DICOM Image display properly in other viewers? Could you provide an anonymized sample image?

Thanks,

Erik

**Comment by MAhmedSaeed** [comment] 2016-02-16 11:12
Hi swederik,

yes the images displayed well in other viewers


![otherviewer](https://cloud.githubusercontent.com/assets/17268318/13074627/532848ea-d4ae-11e5-8a39-26d67fc73817.jpg)

![cornerstoneoutput](https://cloud.githubusercontent.com/assets/17268318/13074508/94dcfc0a-d4ad-11e5-9c37-29d8f2aa07db.jpg)

**Comment by MAhmedSaeed** [comment] 2016-02-16 11:21
dicom image 
http://www.megafileupload.com/ew52/Pub.image.20160216101216.16.dcm.rar

**Comment by swederik** [comment] 2016-02-16 11:30
Hmm that is worrying indeed, but I don't think it's an issue with the photometric interpretation, but probably the transfer syntax (1.2.840.10008.1.2.4.57): JPEG Lossless, Nonhierarchical (Processes 14).

When decompressed the file displays correctly:

![screenshot 2016-02-16 12 30 00](https://cloud.githubusercontent.com/assets/607793/13075097/0ee999cc-d4a9-11e5-9371-9b2204e7b875.png)

Thanks for the report. We will try to look into it.

**Comment by MAhmedSaeed** [comment] 2016-02-16 11:38
Thank you Erik, i appreciate your help

**Comment by chafey** [comment] 2016-02-16 13:12
Chrome is reporting this link as malware and won't let me download it.  Can you post it somewhere else (assuming it is in fact not malware lol).  The min pixel values are coming out as max pixel values which is often caused by signed data related bugs - either in the compression decoder or in cornerstone's use of the decoder (I don't think cornerstone itself has any signed data related bugs)

**Comment by malaterre** [comment] 2016-02-16 13:16
@chafey I had the same issue with chrome, just click "yes i understand" in the download page (Ctrl+J)

**Comment by MAhmedSaeed** [comment] 2016-02-16 13:47
@chafey I hope you can download this file 

https://drive.google.com/file/d/0B7SF2JRjP5AtWVloV1diU1FkYlk/view?usp=sharing

**Comment by chafey** [comment] 2016-02-16 13:56
OK I looked at the image and I think the problem is with the jpeg lossless decoder.  Can you try opening an issue here:

https://github.com/rii-mango/JPEGLosslessDecoderJS

And see if they can fix it?

**Comment by MAhmedSaeed** [comment] 2016-02-17 08:19
it should be fixed by @rii-mango

**Comment by chafey** [comment] 2016-02-17 14:55
Fixed in version 0.9.2 of cornerstoneWADOImageLoader.  Thanks for the bug report!

**Closed by chafey** 2016-02-17 14:55 UTC

**Comment by MAhmedSaeed** [comment] 2017-03-02 07:42
Hi,
I think the issue appears appears again in cornerstone-wado-image-loader - v0.14.2

**Comment by MAhmedSaeed** [comment] 2017-03-02 07:44
![untitled](https://cloud.githubusercontent.com/assets/17268318/23497639/ccf9e710-ff2c-11e6-896d-456878a2be50.jpg)

**Comment by MAhmedSaeed** [comment] 2017-03-02 07:45
the original dicom
![untitled](https://cloud.githubusercontent.com/assets/17268318/23497682/01b7eeca-ff2d-11e6-9e11-6b7cf4a7f33c.jpg)

**Comment by MAhmedSaeed** [comment] 2017-03-02 08:00
[](https://drive.google.com/open?id=0B7SF2JRjP5AtelNIQnhnWTROMTQ)

**Comment by MAhmedSaeed** [comment] 2017-03-02 08:00
https://drive.google.com/open?id=0B7SF2JRjP5AtelNIQnhnWTROMTQ

**Comment by martinezmj** [comment] 2017-03-02 22:19
It's a regression in JPEGLosslessDecoderJS due to some recent performance improvements.  I'll get it fixed (and add a test this time).
