### ISSUE TITLE
Function purgeCacheIfNecessary is throwing Typeerror: lastCachedImage.imagePromise.reject is not a function

### ISSUE THREAD

**Issue by DeepthiN2014** [chafey/cornerstone#91] opened 2017-02-24 04:43 UTC
Hi,

I am using cornerstone.js (cornerstone - v0.10.10) and for mobile application i have reduced the cache to 320MB by setting var maximumSizeInBytes = 335544320; // 320 MB. and once the cache size reaches this value while performing cine functionality :- Cache Size:335544320 it throws the error :- Typeerror: lastCachedImage.imagePromise.reject is not a function and further it will not perform any operation.

Thanks in advance @chafey

**Comment by swederik** [comment] 2017-04-06 07:54
Hi there,

This should be fixed in the latest version of the CornerstoneWADOImageLoader. The relevant commit is here: https://github.com/chafey/cornerstoneWADOImageLoader/commit/5e3aaabb81e6c49c4835ea23bd8c671b9da5faf4

The problem is that we were returning a promise, which doesn't have the reject function.

**Closed by swederik** 2017-04-06 07:54 UTC
Labels: bug
