### ISSUE TITLE
Cornerstone serious compatibility problems in MAC system

### ISSUE THREAD

**Issue by gjun-neusoft** [chafey/cornerstone#95] opened 2017-02-27 16:31 UTC
Loading multiple pictures will appear image loading sequence error. Loading A, B, C, D four pictures, and finally show B, C, D, D four pictures. And no A pictures. When using cornerstoneTools activate a tool, the first picture will change. Image display is not accurate, cornerstoneTools tool switching, this bug is more obvious.

**Comment by jpambrun** [comment] 2017-02-27 16:37
This looks like a duplicate of #94, why did you open another issue? You should edit/comment #94.

**Closed by jpambrun** 2017-02-27 16:37 UTC
