### ISSUE TITLE
Non-default ww/wc values cause rendering delays

### ISSUE THREAD

**Issue by dannyrb** [chafey/cornerstone#164] opened 2017-09-20 17:57 UTC
When I attempt to load and display a cached image, my average render time is < 10ms. If the `windowWidth` or `windowCenter` value is changed from their default values, the render time jumps to ~ 150ms.

I'm using a modified version of the `cornerstoneWebImageLoader` where the only change can be found in the `createImage.js` file:

```
    windowCenter: voiLutModule.windowCenter ? voiLutModule.windowCenter[0] : 128,
    windowWidth: voiLutModule.windowWidth ? voiLutModule.windowWidth[0] : 255,
```

If the numbers are anything other than the defaults. I experience the rendering issue. Similarly, I can update the ww/wc values by clicking and dragging using the following `cornerstoneTools` tool:

`cornerstoneTools.wwwc.activate(element, 1);`

I also experience rendering delays if the `ww/wc` values were updated by the tool. This issue only appears to happen in the Google Chrome browser. I am using the following version: `Version 61.0.3163.91 (Official Build) (64-bit)`

This may be related to #108

**Comment by swederik** [comment] 2017-09-21 09:21
Are you using the WebGL renderer? If so, it might be a duplicate of https://github.com/chafey/cornerstone/issues/134

Are you loading cornerstone as an NPM module?

**Comment by swederik** [comment] 2017-10-26 15:11
Is this still happening?

**Comment by dannyrb** [comment] 2017-10-26 19:21
I'm having issues getting the latest `external` import/configuration stuff to work with my app. I'll create a smaller codepen tomorrow to test with latest and report back 👍

**Comment by swederik** [comment] 2017-11-03 14:03
I noticed some oddities in renderWebImage that might have caused this bug. I am going to address it and I have some changes in this PR (See https://github.com/chafey/cornerstone/pull/187/files#diff-774d6b6778b2d902f74becc5859366ddR27)

**Closed** 2017-11-07 09:24 UTC
Labels: bug, performance

**Comment by swederik** [comment] 2017-11-07 09:25
I don't know if my commit definitively fixed this issue, but the commit did address the case where for non-default ww/wc values, renderColorImage would be run after renderWebImage, so quite a bit of the drawing functions were being run twice.

Feel free to reopen if you still have the issue!
